// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCyBTVep89OyXcXt6a5G85Qf6xe5cgu8ZA',
    appId: '1:575174458424:web:0de4e270c99b21446abacd',
    messagingSenderId: '575174458424',
    projectId: 'car-maintenance-app-eb5bb',
    authDomain: 'car-maintenance-app-eb5bb.firebaseapp.com',
    storageBucket: 'car-maintenance-app-eb5bb.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAF3-k-w5eXrpWxolT0LCa4Iwm_0M6c75s',
    appId: '1:575174458424:android:eb74706725ec12d96abacd',
    messagingSenderId: '575174458424',
    projectId: 'car-maintenance-app-eb5bb',
    storageBucket: 'car-maintenance-app-eb5bb.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBtG0v75Zqqp3IcpwZpVnusSQb9Y37H1p0',
    appId: '1:575174458424:ios:d27be883bd8c47016abacd',
    messagingSenderId: '575174458424',
    projectId: 'car-maintenance-app-eb5bb',
    storageBucket: 'car-maintenance-app-eb5bb.firebasestorage.app',
    iosBundleId: 'com.example.carMaintenance',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBtG0v75Zqqp3IcpwZpVnusSQb9Y37H1p0',
    appId: '1:575174458424:ios:d27be883bd8c47016abacd',
    messagingSenderId: '575174458424',
    projectId: 'car-maintenance-app-eb5bb',
    storageBucket: 'car-maintenance-app-eb5bb.firebasestorage.app',
    iosBundleId: 'com.example.carMaintenance',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCyBTVep89OyXcXt6a5G85Qf6xe5cgu8ZA',
    appId: '1:575174458424:web:de36d6a28e36c76f6abacd',
    messagingSenderId: '575174458424',
    projectId: 'car-maintenance-app-eb5bb',
    authDomain: 'car-maintenance-app-eb5bb.firebaseapp.com',
    storageBucket: 'car-maintenance-app-eb5bb.firebasestorage.app',
  );
}
